### ISSUE TITLE
Video and audio out of sync/ Video lagging behind audio.  

### ISSUE THREAD

**Issue by fredlemieux** [GoogleChrome/omnitone#24] opened 2016-10-10 17:37 UTC
I'm really impressed by the Omnitone examples, except with the audio being out of sync with the video.

The video appears to be going slower that the audio.  If I press pause, when I start playing the video jumps forward to where it is supposed to be.  I thought that it may be an issue with it streaming over the net, so I've tried running the demo off my own via a localhost and still has the same problem.

Is anybody also getting this problem?  

I thought that it may be because of ambisonic decoding but you would expect the audio to be behind the video, not the other way round.

**Comment by hoch** [comment] 2016-10-10 17:44
> The video appears to be going slower that the audio. If I press pause, when I start playing the video jumps forward to where it is supposed to be. I thought that it may be an issue with it streaming over the net, so I've tried running the demo off my own via a localhost and still has the same problem.

I can't reproduce this issue with the current stable version of Chrome. (m53) What's your browser and version?

**Comment by hoch** [comment] 2016-10-24 18:57
@fredlemieux Can you provide more information?

**Comment by hoch** [comment] 2017-02-14 17:26
@fredlemieux Any feedback? Without triaging the issue properly, it's really hard to fix.

**Comment by hoch** [comment] 2017-03-20 22:51
@fredlemieux It has been almost 5 months without feedback, so I am closing this. Please re-open the issue if the problem persists.

**Closed by hoch** 2017-03-20 22:51 UTC
Labels: unconfirmed
